### ISSUE TITLE
mesheryctl build broken after fixing lint issues.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#245]
**Description**
`mesheryctl` build broken after fixing lint issues in #238.

**make output**
```meshery git:(master) make
cd mesheryctl; go build -o mesheryctl
go: finding github.com/dgraph-io/badger v1.6.0
go: finding github.com/dgryski/go-farm v0.0.0-20190423205320-6a90982ecee2
go: finding github.com/AndreasBriese/bbloom v0.0.0-20190306092124-e2d15f34fcf9
go: finding golang.org/x/sys v0.0.0-20190626221950-04f50cda93cb
# github.com/layer5io/meshery/mesheryctl/cmd
cmd/init.go:33:22: undefined: Prereq
cmd/init.go:36:14: undefined: DownloadFile
cmd/start.go:41:13: undefined: DownloadFile
cmd/start.go:41:45: undefined: fileUrl
cmd/stop.go:37:13: undefined: DownloadFile
cmd/stop.go:37:45: undefined: fileUrl
make: *** [make] Error 2```

**Comment by girishranganathan** [comment]
#249 fixes this issue. Please feel free to reopen it if needed.
